captureDirectory: 'capturing'
completeDirectory: 'captured'
modelScanInterval: 300
debug: true
models:
  - 10272360 # XViciousLoveX
  - 10876762 # JadineIsNasty
  - 11549213 # Jayde_Phoenix
  - 15042071 # Tat2peach
  - 15406039 # StunningAna
  - 16915028 # AriannaSecret
  - 17030607 # oKRYSTALo
  - 21090122 # Cutekitty747
  - 21310821 # Beawolfx
  - 21322349 # beawolfxo
  - 21578748 # Lolasays
  - 2530502 # AdorableKye
  - 8339561 # kannalol
  - 8450555 # AlisOnFire
  - 9759444 # Geniva_
  - 9798847 # B_E_L_L_E_
includeModels:
  - MODELNAMETOSTARTCAPTURING
excludeModels:
  - MODELNAMETOSTOPCAPTURING